// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//
// Build-time codegen for the WTA ETW TraceLogging provider.
//
// WTA registers its own provider, `Microsoft.Windows.Terminal.WTA`. The Microsoft
// telemetry group GUID + keyword/privacy values come from `ProjectTelemetry.h`,
// resolved the same way the C++ include path does (`src\inc` before `dep`):
//   - src/inc/telemetry/ProjectTelemetry.h  real header overlaid by the
//                                           `terminal-internals` package (official builds)
//   - dep/telemetry/ProjectTelemetry.h      OSS stub fallback (placeholder group
//                                           GUID + zero keyword/privacy => not collected)
// For the overlay to exist at cargo-build time, the pipeline downloads
// `terminal-internals` in `beforeRustBuildSteps` (before `cargo build`).
//
// No external build-dependencies (no `regex` crate): hand-rolled scanning of one
// small header keeps the build closure flat.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// WTA's own ETW provider name; the `tracelogging` crate derives the matching
/// GUID `{4cfcff80-4e6b-5bfd-8ea1-d38e1226f70b}` from it.
const PROVIDER_NAME: &str = "Microsoft.Windows.Terminal.WTA";

fn main() {
    // Set the default thread stack size to 8 MB on Windows debug builds.
    //
    // Why this is needed:
    //   rust-i18n v3 embeds all translations at compile time. Each `t!()`
    //   call-site expands into a match over every available locale (~89).
    //   In unoptimized (debug) builds the compiler does not collapse these
    //   match arms, so functions that contain several `t!()` calls produce
    //   stack frames large enough to overflow the default 1 MB stack.
    //
    //   Release builds are unaffected — the optimizer folds the match arms
    //   and keeps stack usage well within 1 MB.
    //
    // 8 MB is a conservative choice — many Windows desktop applications
    // (including the .NET CLR) default to 4–8 MB stacks.
    #[cfg(all(debug_assertions, target_os = "windows", target_env = "msvc"))]
    println!("cargo:rustc-link-arg=/STACK:8388608");

    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // tools/wta -> repo root
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .unwrap_or_else(|| panic!("could not derive repo root from {}", manifest_dir.display()))
        .to_path_buf();

    // Resolve the telemetry header the same way the C++ include path does
    // (`src\inc` before `dep`): real header overlaid at `src/inc/...` by the
    // `terminal-internals` package in official builds; OSS falls back to the stub.
    let overlay = repo_root.join("src/inc/telemetry/ProjectTelemetry.h");
    let stub = repo_root.join("dep/telemetry/ProjectTelemetry.h");
    let proj_tel_h = if overlay.exists() { overlay.clone() } else { stub.clone() };

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", overlay.display());
    println!("cargo:rerun-if-changed={}", stub.display());

    let provider_name = PROVIDER_NAME;
    let group_guid = parse_group_guid(&proj_tel_h);
    let keyword_measures = extract_define_u64(&proj_tel_h, "MICROSOFT_KEYWORD_MEASURES");
    let keyword_telemetry = extract_define_u64(&proj_tel_h, "MICROSOFT_KEYWORD_TELEMETRY");
    let privacy_usage = extract_define_u64(&proj_tel_h, "PDT_ProductAndServiceUsage");
    let privacy_perf = extract_define_u64(&proj_tel_h, "PDT_ProductAndServicePerformance");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("telemetry_codegen.rs");
    let generated = format!(
        "// Generated by build.rs from:\n\
         //   {proj_tel_h}\n\
         // Do not edit by hand.\n\
         \n\
         tracelogging::define_provider!(\n    \
             AGENT_PROVIDER,\n    \
             {provider_name:?},\n    \
             group_id({group_id:?})\n\
         );\n\
         \n\
         #[allow(dead_code)]\n\
         pub const MICROSOFT_KEYWORD_MEASURES: u64 = {keyword_measures:#x};\n\
         #[allow(dead_code)]\n\
         pub const MICROSOFT_KEYWORD_TELEMETRY: u64 = {keyword_telemetry:#x};\n\
         pub const PDT_PRODUCT_AND_SERVICE_USAGE: u64 = {privacy_usage:#x};\n\
         pub const PDT_PRODUCT_AND_SERVICE_PERFORMANCE: u64 = {privacy_perf:#x};\n",
        proj_tel_h = proj_tel_h.display(),
        provider_name = provider_name,
        group_id = group_guid,
        keyword_measures = keyword_measures,
        keyword_telemetry = keyword_telemetry,
        privacy_usage = privacy_usage,
        privacy_perf = privacy_perf,
    );
    fs::write(&out_path, generated).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out_path.display());
    });
}

/// Extract the Microsoft telemetry group GUID from the
/// `TraceLoggingOptionGroup(0x.., 0x.., ...)` macro (11 hex fields: u32, u16,
/// u16, then 8 bytes). Any malformation panics -> build fails.
fn parse_group_guid(path: &Path) -> String {
    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    let inner = text
        .split_once("TraceLoggingOptionGroup(")
        .and_then(|(_, r)| r.split_once(')'))
        .unwrap_or_else(|| panic!("group GUID macro not found in {}", path.display()))
        .0;
    let f: Vec<u64> = inner
        .split(',')
        .map(|p| {
            let tok = p.trim();
            // Accept both `0x` and `0X`, matching `extract_define_u64`.
            let hex = tok
                .strip_prefix("0x")
                .or_else(|| tok.strip_prefix("0X"))
                .unwrap_or(tok);
            // Tolerate a trailing C numeric suffix (`u`/`U`/`l`/`L`); none of
            // these are hex digits, so this can't strip real value bytes.
            let hex = hex.trim_end_matches(|c: char| matches!(c, 'u' | 'U' | 'l' | 'L'));
            u64::from_str_radix(hex, 16).unwrap_or_else(|e| {
                panic!(
                    "failed to parse group GUID field `{tok}` in {}: {e}",
                    path.display()
                )
            })
        })
        .collect();
    assert_eq!(f.len(), 11, "group GUID: expected 11 fields, got {}", f.len());
    format!(
        "{:08x}-{:04x}-{:04x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}",
        f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8], f[9], f[10]
    )
}

/// Parse a `#define NAME <integer>` line, accepting common C numeric
/// suffixes (`u`, `U`, `ul`, `ULL`, …) and both hex (`0x...`) and decimal
/// literals. Panics if the constant is missing.
fn extract_define_u64(path: &Path, name: &str) -> u64 {
    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    for line in text.lines() {
        let trimmed = line.trim_start();
        let rest = match trimmed.strip_prefix("#define") {
            Some(r) => r.trim_start(),
            None => continue,
        };
        let rest = match rest.strip_prefix(name) {
            // The character immediately after `name` must not be an
            // identifier-continuation char; without this guard
            // `MICROSOFT_KEYWORD_X` would also match `MICROSOFT_KEYWORD_XY`.
            Some(r) if r.chars().next().is_none_or(|c| !is_ident_continue(c)) => r.trim_start(),
            _ => continue,
        };
        // Strip a trailing comment, if any.
        let value_text = rest
            .split_once("//")
            .map(|(v, _)| v)
            .unwrap_or(rest)
            .trim();
        // Strip a C numeric suffix.
        let digits_end = value_text
            .find(|c: char| !(c.is_ascii_hexdigit() || c == 'x' || c == 'X'))
            .unwrap_or(value_text.len());
        let digits = &value_text[..digits_end];
        let parsed = if let Some(hex) = digits.strip_prefix("0x").or_else(|| digits.strip_prefix("0X")) {
            u64::from_str_radix(hex, 16)
        } else {
            digits.parse::<u64>()
        };
        return parsed.unwrap_or_else(|e| {
            panic!(
                "failed to parse `#define {name} {value_text}` in {}: {e}",
                path.display()
            )
        });
    }
    panic!(
        "`#define {name} ...` not found in {}; the file layout this build.rs depends on has changed",
        path.display()
    );
}

fn is_ident_continue(c: char) -> bool {
    c == '_' || c.is_ascii_alphanumeric()
}
