// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//
// ETW TraceLogging provider for the WTA (Windows Terminal Agent) process.
//
// WTA registers its own provider, `Microsoft.Windows.Terminal.WTA`. The
// provider definition and the keyword/privacy constants are
// generated by `build.rs`, which reads the Microsoft telemetry group GUID +
// keyword + privacy values from `ProjectTelemetry.h` (real values overlaid by
// the `terminal-internals` package in official builds; OSS stub => inert). See
// `build.rs` for header resolution.
//
// Note: the `SessionId` field on WTA events identifies the ACP session
// (agent-pane backend connection); join to C++-side events only via fields
// explicitly shared (e.g. `PaneId`).
//
// Events emitted from this module:
//   - AcpInitializeComplete  (ACP initialize RPC completes)
//   - AcpNewSessionComplete  (ACP session/new RPC completes)
//   - AgentPromptSent          (WTA dispatches a prompt over ACP)
//   - AgentResponseFirstToken  (ACP returns the first text chunk)
//   - AgentResponseComplete    (ACP prompt request completes)
//   - ErrorDetected            (classify_wt_event positively classifies an error)
//   - ErrorFixResolved         (next command's exit code is 0 after a fix attempt)
//
// Conventions:
//   - Per-event description: documented in the Rust doc comment above each
//     `log_*` wrapper in this file. The `tracelogging` crate's `write_event!`
//     macro does not surface a TraceLoggingDescription-equivalent metadata
//     field at the wire level, so the human-readable description lives in
//     source (and in this module's per-event subsection below) rather than
//     in the event payload.
//   - Keyword: MICROSOFT_KEYWORD_MEASURES (stub = 0 in OSS; real value in MS-internal build)
//   - PartA_PrivTags: per-event — `ErrorDetected` / `ErrorFixResolved` /
//     `AgentPromptSent` use `PDT_ProductAndServiceUsage` (usage-tagged
//     product signals), while the latency-bearing
//     `AgentResponseFirstToken` and `AgentResponseComplete` use
//     `PDT_ProductAndServicePerformance` (the durations they carry are
//     perf metrics, not usage counters).
//   - Level: `Verbose`, matching `TraceLoggingWrite`'s C++ default (the C++
//     events under this provider also use the implicit Verbose level).

use tracelogging as tlg;

// Provider definition + telemetry constants — generated by `build.rs` from the
// telemetry header (`ProjectTelemetry.h`). See the build script for header
// resolution and the panic-on-miss policy.
include!(concat!(env!("OUT_DIR"), "/telemetry_codegen.rs"));

/// Register the ETW provider. Safe to call multiple times — the underlying
/// `TraceLoggingRegister`-style API is guarded by a `Once`, so only the
/// first invocation actually performs the (unsafe) registration. Subsequent
/// calls are no-ops, which keeps tests and repeated startup paths safe.
///
/// # Safety
/// `TraceLoggingRegister`-style APIs are inherently per-process. The
/// `tracelogging` crate marks `register()` `unsafe` for that reason. The
/// `Once` below guarantees the unsafe call runs exactly once.
pub fn register() {
    static REGISTER_ONCE: std::sync::Once = std::sync::Once::new();
    REGISTER_ONCE.call_once(|| {
        // SAFETY: the surrounding `Once` guarantees this runs exactly once
        // per process; `tracelogging`'s contract is satisfied.
        unsafe {
            AGENT_PROVIDER.register();
        }
    });
}

/// Unregister the ETW provider. Optional; the OS reclaims the registration
/// on process exit. No-op if `register()` was never called.
#[allow(dead_code)]
pub fn unregister() {
    AGENT_PROVIDER.unregister();
}

/// Emitted when an ACP `initialize` RPC completes. `duration_ms` is a
/// monotonic duration measured around the RPC attempt, not wall-clock.
///
/// `route` identifies the WTA path that issued the RPC (for example,
/// master startup versus direct agent mode) so downstream queries can avoid
/// mixing cached/helper handshakes with agent CLI handshakes.
///
/// `failure_kind` is empty on success, `Timeout` when no response arrived
/// before the local timeout, or `AcpError` when the agent returned a
/// JSON-RPC/ACP error. `acp_error_code` is the agent-provided code for
/// `AcpError`; otherwise it is 0.
pub fn log_acp_initialize_complete(
    duration_ms: f64,
    success: bool,
    route: &str,
    failure_kind: &str,
    acp_error_code: i32,
) {
    let success_i32: i32 = if success { 1 } else { 0 };
    tlg::write_event!(
        AGENT_PROVIDER,
        "AcpInitializeComplete",
        level(Verbose),
        keyword(MICROSOFT_KEYWORD_MEASURES),
        f64("DurationMs", &duration_ms),
        bool32("Success", &success_i32),
        str8("Route", route),
        str8("FailureKind", failure_kind),
        i32("AcpErrorCode", &acp_error_code),
        u64("PartA_PrivTags", &PDT_PRODUCT_AND_SERVICE_PERFORMANCE),
    );
}

/// Emitted when an ACP `session/new` RPC completes. `duration_ms` is a
/// monotonic duration measured around the RPC attempt, not wall-clock.
///
/// `session_id` is present only on success. Failed attempts still emit the
/// event with an empty `SessionId` so the ETW schema remains stable.
///
/// `failure_kind` is empty on success, `Timeout` when no response arrived
/// before the local timeout, or `AcpError` when the agent returned a
/// JSON-RPC/ACP error. `acp_error_code` is the agent-provided code for
/// `AcpError`; otherwise it is 0.
pub fn log_acp_new_session_complete(
    session_id: Option<&str>,
    duration_ms: f64,
    success: bool,
    route: &str,
    failure_kind: &str,
    acp_error_code: i32,
) {
    let success_i32: i32 = if success { 1 } else { 0 };
    let session_id = session_id.unwrap_or("");
    tlg::write_event!(
        AGENT_PROVIDER,
        "AcpNewSessionComplete",
        level(Verbose),
        keyword(MICROSOFT_KEYWORD_MEASURES),
        str8("SessionId", session_id),
        f64("DurationMs", &duration_ms),
        bool32("Success", &success_i32),
        str8("Route", route),
        str8("FailureKind", failure_kind),
        i32("AcpErrorCode", &acp_error_code),
        u64("PartA_PrivTags", &PDT_PRODUCT_AND_SERVICE_PERFORMANCE),
    );
}

/// Emitted when WTA dispatches a prompt over the ACP stream to an agent.
///
/// Covers the agent-pane prompt-entry route. The C++ side emits its own
/// related event for the `?<prompt>` command-palette delegation route
/// (`CommandPaletteDispatchedAgentPrompt` in
/// `src/cascadia/TerminalApp/CommandPalette.cpp`, under the same provider).
pub fn log_agent_prompt_sent(
    session_id: &str,
    prompt_byte_len: u32,
    is_autofix: bool,
    template_kind: &str,
) {
    let is_autofix_i32: i32 = if is_autofix { 1 } else { 0 };
    tlg::write_event!(
        AGENT_PROVIDER,
        "AgentPromptSent",
        level(Verbose),
        keyword(MICROSOFT_KEYWORD_MEASURES),
        str8("SessionId", session_id),
        u32("PromptLengthBytes", &prompt_byte_len),
        bool32("IsAutofix", &is_autofix_i32),
        str8("TemplateKind", template_kind),
        str8("Route", "AcpDispatch"),
        u64("PartA_PrivTags", &PDT_PRODUCT_AND_SERVICE_USAGE),
    );
}

/// Emitted when the agent's first text chunk arrives back over ACP.
/// `first_token_latency_ms` is a monotonic duration (`Instant::elapsed`)
/// from prompt dispatch to first token, not wall-clock.
///
/// Uses a distinct event name (`AgentResponseFirstToken`) so the field
/// schema is unambiguous in downstream decoders — keeping a single
/// `AgentResponseReceived` name across the first-token and complete cases
/// would yield two metadata definitions for the same event name in ETW
/// (the schemas differ), which complicates query/decode.
pub fn log_agent_response_first_token(
    session_id: &str,
    first_token_latency_ms: f64,
    chunk_byte_len: u32,
) {
    tlg::write_event!(
        AGENT_PROVIDER,
        "AgentResponseFirstToken",
        level(Verbose),
        keyword(MICROSOFT_KEYWORD_MEASURES),
        str8("SessionId", session_id),
        f64("FirstTokenLatencyMs", &first_token_latency_ms),
        u32("ChunkLengthBytes", &chunk_byte_len),
        u64("PartA_PrivTags", &PDT_PRODUCT_AND_SERVICE_PERFORMANCE),
    );
}

/// Emitted when the agent finishes responding (prompt request completes).
/// `total_duration_ms` is a monotonic duration (`Instant::elapsed`) from
/// prompt dispatch to completion, not wall-clock.
/// `raw_stdout_bytes_after_prompt` was the raw transport byte count read
/// from the agent CLI's stdout after the prompt was dispatched (JSON-RPC
/// framing / tool-call payloads included — a transport-level volume metric,
/// not a measure of the final answer length).
///
/// NOTE: this is currently always 0. The stdout-read instrumentation lived
/// in the direct agent-spawn path (`StartupInstrumentedReader`), which was
/// removed when WTA moved to the master/helper architecture: a helper speaks
/// ACP to wta-master over a named pipe and never reads the agent CLI's stdout
/// directly — master owns that transport. The `raw_stdout_bytes_after_prompt`
/// argument and the `TotalResponseBytes` ETW field are kept (always 0) for
/// downstream schema compatibility; reintroducing the metric would mean
/// accounting bytes at the master↔agent boundary. Until then, treat
/// `TotalResponseBytes` as unpopulated rather than a per-session byte count.
///
/// Uses a distinct event name (`AgentResponseComplete`) — see the note on
/// `log_agent_response_first_token` for why this is split into two events.
pub fn log_agent_response_complete(
    session_id: &str,
    total_duration_ms: f64,
    raw_stdout_bytes_after_prompt: u64,
    success: bool,
) {
    let success_i32: i32 = if success { 1 } else { 0 };
    tlg::write_event!(
        AGENT_PROVIDER,
        "AgentResponseComplete",
        level(Verbose),
        keyword(MICROSOFT_KEYWORD_MEASURES),
        str8("SessionId", session_id),
        f64("TotalDurationMs", &total_duration_ms),
        u64("TotalResponseBytes", &raw_stdout_bytes_after_prompt),
        bool32("Success", &success_i32),
        u64("PartA_PrivTags", &PDT_PRODUCT_AND_SERVICE_PERFORMANCE),
    );
}

/// Emitted when the WTA event classifier positively identifies an error in
/// a pane (e.g., connection failed, process exited with non-zero code).
pub fn log_error_detected(severity: &str, method: &str, pane_id: &str) {
    tlg::write_event!(
        AGENT_PROVIDER,
        "ErrorDetected",
        level(Verbose),
        keyword(MICROSOFT_KEYWORD_MEASURES),
        str8("Severity", severity),
        str8("Method", method),
        str8("PaneId", pane_id),
        u64("PartA_PrivTags", &PDT_PRODUCT_AND_SERVICE_USAGE),
    );
}

/// Emitted when the next command after an attempted fix succeeds (exit 0)
/// in the same pane where autofix was armed. `time_since_fix_ms` is a
/// monotonic duration (`Instant::elapsed`) from arming the fix to observing
/// the successful exit, not wall-clock.
pub fn log_error_fix_resolved(pane_id: &str, time_since_fix_ms: f64) {
    tlg::write_event!(
        AGENT_PROVIDER,
        "ErrorFixResolved",
        level(Verbose),
        keyword(MICROSOFT_KEYWORD_MEASURES),
        str8("PaneId", pane_id),
        f64("TimeSinceFixMs", &time_since_fix_ms),
        u64("PartA_PrivTags", &PDT_PRODUCT_AND_SERVICE_USAGE),
    );
}
